language: php
script: make test

php:
  - 5.3
  - 5.4

before_script:
  - "sudo make dev-travis"
  - "pyrus channel-discover pear.symfony.com"
  - "pyrus channel-discover packages.zendframework.com"
  - "phpenv rehash" 
